<style scoped>
    .subtitle {
        font-size: 1rem;
    }
</style>

<template>
    <div>
        <h2 class="title is-size-3 mb-half">
            What others say about
        </h2>

        <div class="field">
            <div class="control has-icons-left">
                <div class="select is-inline-block">
                    <select v-model="query">
                        <option :value="value" v-for="(label, value) in queries">
                            {{ label }}
                        </option>
                    </select>
                </div>
                <div class="icon is-left" style="color: #363636">
                    the
                </div>
            </div>
        </div>

        <NNBarChart :nn="filteredNN" />

        <span class="subtitle">
            Keywords automatically generated by
            <a rel="noopener" :href="embedding.url">
                {{ embedding.name }}
            </a>
        </span>
    </div>
</template>

<script>
    import NNBarChart from './NNBarChart';

    export default {
        name: 'NN',
        components: {
            NNBarChart
        },
        props: {
            nn: {
                type: Array,
                required: true
            },
            embedding: {
                type: Object,
                required: true
            }
        },
        data() {
            const queries = {
                tast: 'Taste',
                palat: 'Palate',
                overal: 'Overall',
                aroma: 'Aroma',
                appear: 'Appearance',
                pour: 'Pour',
                bottl: 'Bottle',
                price: 'Price',
                color: 'Color',
                smell: 'Smell'
            };

            return {
                query: 'tast',
                queries: queries
            };
        },
        computed: {
            filteredNN() {
                return this.nn.filter(nn => nn.query === this.query);
            }
        }
    }
</script>